import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const strategy = z.enum(["fake", "local", "real", "claudecode"]).default("fake");

export const env = createEnv({
  server: {
    AUTH0_DOMAIN: z.string().min(1),
    AUTH0_CLIENT_ID: z.string().min(1),
    AUTH0_CLIENT_SECRET: z.string().min(1),
    AUTH0_SECRET: z.string().min(1),
    AUTH0_AUDIENCE: z.string().min(1),

    APP_BASE_URL: z.string().url().optional(),

    BLOB_READ_WRITE_TOKEN: z.string().min(1).optional(),
    BLOB_STORE_NAME: z.string().min(1).default("documents"),

    SMARTY_STRATEGY: strategy,
    TEXTRACT_STRATEGY: strategy,
    SENDGRID_STRATEGY: strategy,
    TWILIO_STRATEGY: strategy,
    DROPBOX_SIGN_STRATEGY: strategy,
    SIMPLIFILE_STRATEGY: strategy,
    EASYPOST_STRATEGY: strategy,
    PLAID_STRATEGY: strategy,
    ATTOM_STRATEGY: strategy,

    AI_GATEWAY_API_KEY: z.string().min(1).optional(),
    EMPORA_MCP_URL: z.string().url().optional(),

    CRON_SECRET: z.string().min(1).optional(),

    EMPORA_ADMIN_MCP_URL: z.string().url().optional(),
    EMPORA_ADMIN_MCP_TOKEN: z.string().min(1).optional(),

    SMARTY_AUTH_ID: z.string().min(1).optional(),
    SMARTY_AUTH_TOKEN: z.string().min(1).optional(),
    SENDGRID_API_KEY: z.string().min(1).optional(),
    TWILIO_ACCOUNT_SID: z.string().min(1).optional(),
    TWILIO_AUTH_TOKEN: z.string().min(1).optional(),
    DROPBOX_SIGN_API_KEY: z.string().min(1).optional(),
    DROPBOX_SIGN_CLIENT_ID: z.string().min(1).optional(),
    SIMPLIFILE_API_KEY: z.string().min(1).optional(),
    SIMPLIFILE_API_URL: z.string().url().optional(),
    SIMPLIFILE_SUBMITTER_ID: z.string().min(1).optional(),
    EASYPOST_API_KEY: z.string().min(1).optional(),
    PLAID_CLIENT_ID: z.string().min(1).optional(),
    PLAID_SECRET: z.string().min(1).optional(),
    ATTOM_API_KEY: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_CONVEX_URL: z.string().url(),
  },
  runtimeEnv: {
    AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
    AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
    AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET,
    AUTH0_SECRET: process.env.AUTH0_SECRET,
    AUTH0_AUDIENCE: process.env.AUTH0_AUDIENCE,
    APP_BASE_URL: process.env.APP_BASE_URL,
    NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    BLOB_STORE_NAME: process.env.BLOB_STORE_NAME,
    SMARTY_STRATEGY: process.env.SMARTY_STRATEGY,
    TEXTRACT_STRATEGY: process.env.TEXTRACT_STRATEGY,
    SENDGRID_STRATEGY: process.env.SENDGRID_STRATEGY,
    TWILIO_STRATEGY: process.env.TWILIO_STRATEGY,
    DROPBOX_SIGN_STRATEGY: process.env.DROPBOX_SIGN_STRATEGY,
    SIMPLIFILE_STRATEGY: process.env.SIMPLIFILE_STRATEGY,
    EASYPOST_STRATEGY: process.env.EASYPOST_STRATEGY,
    PLAID_STRATEGY: process.env.PLAID_STRATEGY,
    ATTOM_STRATEGY: process.env.ATTOM_STRATEGY,
    AI_GATEWAY_API_KEY: process.env.AI_GATEWAY_API_KEY,
    EMPORA_MCP_URL: process.env.EMPORA_MCP_URL,
    CRON_SECRET: process.env.CRON_SECRET,
    EMPORA_ADMIN_MCP_URL: process.env.EMPORA_ADMIN_MCP_URL,
    EMPORA_ADMIN_MCP_TOKEN: process.env.EMPORA_ADMIN_MCP_TOKEN,
    SMARTY_AUTH_ID: process.env.SMARTY_AUTH_ID,
    SMARTY_AUTH_TOKEN: process.env.SMARTY_AUTH_TOKEN,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
    DROPBOX_SIGN_API_KEY: process.env.DROPBOX_SIGN_API_KEY,
    DROPBOX_SIGN_CLIENT_ID: process.env.DROPBOX_SIGN_CLIENT_ID,
    SIMPLIFILE_API_KEY: process.env.SIMPLIFILE_API_KEY,
    SIMPLIFILE_API_URL: process.env.SIMPLIFILE_API_URL,
    SIMPLIFILE_SUBMITTER_ID: process.env.SIMPLIFILE_SUBMITTER_ID,
    EASYPOST_API_KEY: process.env.EASYPOST_API_KEY,
    PLAID_CLIENT_ID: process.env.PLAID_CLIENT_ID,
    PLAID_SECRET: process.env.PLAID_SECRET,
    ATTOM_API_KEY: process.env.ATTOM_API_KEY,
  },
  emptyStringAsUndefined: true,
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
